### PR TITLE
Updated readme examples to es6

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by vankasteelj** [comment]
that's fairly incomplete, it's a mix of es5 and es6

**Comment by amilajack** [comment]
Sorry about that. For some other repos that I contributed to, the owners didn't allow arrow functions. Just pushed a commit to fix that.

**Comment by vankasteelj** [comment]
well I'm ok with either es5 or es6, but mixing always felt wierd to me. Thanks for your contribution!

**Comment by mdelagrange** [comment]
this didn't work for me. i thought that node didn't support ES6 imports yet.

**Comment by amilajack** [comment]
It assumes that you're using a module loader. Do this instead:

``` js
const Trakt = require('trakt.tv');
```

**Pull request merged**
