### PR TITLE
Added npmignore

### PR DESCRIPTION
**Pull request by amilajack**
Using this module with webpack produces a warning where Webpack attempts to parse the readme because it is not ignored by npm. This changes that.

### CODE REVIEW

**Comment by amilajack** [comment]
The error looks something like this:

```
WARNING in ./~/trakt.tv/README.md
Module parse failed: //node_modules/trakt.tv/README.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
```

**Comment by vankasteelj** [comment]
Won't this prevent any attempt to modify the readme ? I thought npmignore file was used by git if gitignore isn't present, or is it the opposite ?

**Comment by amilajack** [comment]
Oh right I forgot about that. Adding it to the gitignore would mean that the npm homepage of this project would not have a readme. I'm figure out something how to fix it with webpack instead.

**Comment by vankasteelj** [comment]
Ima gonna close this then :p

**Comment by thangngoc89** [comment]
>  Adding it to the gitignore would mean that the npm homepage of this project would not have a readme

This is not true. I can't find where did I read this. But `npm publish` auto publish README.md no matter what

**Comment by amilajack** [comment]
That is true. In my fork, i am still getting this issue. Maybe telling webpack to ignore all *.md files would work.

**Comment by thangngoc89** [comment]
Webpack should not parse README.md in the first place

**Comment by amilajack** [comment]
Just removed the readme.md and I got this error:

```

WARNING in ./~/trakt.tv/index.js
Critical dependencies:
68:29-44 the request of a dependency is an expression
 @ ./~/trakt.tv/index.js 68:29-44

```

On like 68 of index.js, index.js is doing a dynamic require at runtime. Webpack bundles everything in the folder because it doesnt know what will be required at runtime.

**Comment by thangngoc89** [comment]
> Just removed the readme.md and I got this error:

I saw both errors on my side

**Pull request closed without merging**
