### PR TITLE
add shows/last_episode

### PR DESCRIPTION
**Pull request by katz12**
Seems to work locally for me. Is there any reason you didn't include it originally?

### CODE REVIEW

**Comment by vankasteelj** [comment]
it's either something I forgot or that was added recently ? I'll test it next year (hahahahaha)

**Comment by katz12** [comment]
Could be new? It's in the docs under Shows (http://docs.trakt.apiary.io/#introduction/third-party-libraries). There is also next_episode which I will probably add as well.

**Comment by vankasteelj** [comment]
Added: October 11, 2016 -> https://apiblog.trakt.tv/api-changelog-9f4041819718#.306qoifdh

**Comment by vankasteelj** [comment]
Wait, it's already in : https://github.com/vankasteelj/trakt.tv/commit/3da2d8d1a69aca6bc64cee0472cb155a778224e5

**Comment by katz12** [comment]
Ohh whoops I guess I missed that. In the docs its under Shows though.

**Comment by vankasteelj** [comment]
leave this open & i'll check when partying is over, or check it and report back :) happy new year's eve

**Comment by katz12** [comment]
You too. I think the only change to make would be to switch it to shows/*_episode. I'll update my patch and let you decide.

Ugh but this will be a breaking change for anyone currently using episodes.next_episode or episodes.last_episode.

**Comment by vankasteelj** [comment]
indeed, I might have implemented it while being drunk

**Pull request merged**
