### PR TITLE
Let the user set a custom User-Agent header

### PR DESCRIPTION
**Pull request by ghost**
Should be much better now :)

### CODE REVIEW

**Comment by vankasteelj** [comment]
it's merged into dev, thanks. this should close automatically once merged with master. I've expanded on the idea and set my own UA, just in case. But I can't test anything atm as the oauth servers are down

**Comment by ghost** [comment]
Thank you, I got a feature I wanted and you taught me something too :)

**Comment by vankasteelj** [comment]
note that justin from trakt answered me: "We don't currently use the user agent for anything. It makes sense for apps to send something valid as a good practice, but we don't have any plans to use it right now."

**Comment by ghost** [comment]
That's good to know. Strange though, one would think they'd care about figuring out what apps are using the service more heavily.

**Comment by vankasteelj** [comment]
They don't need that, they have API keys as client_id

**Comment by ghost** [comment]
...oh yeah. Lol. Didn't think about that ><

**Pull request merged**
