### PR TITLE
Add `queued` and `cached` to the plugin list

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
As promised :)

**Comment by ghost** [comment]
what the hell? where did all these commits come from?

**Comment by vankasteelj** [comment]
a wrong merge, probably because you pulled

**Comment by ghost** [comment]
I don't get it, I thought I branched from master. Look it's just a couple of lines could you just add them yourself? Sorry for the mess I don't know how I still get this simple stuff wrong D:

**Comment by vankasteelj** [comment]
it's done on dev

**Comment by ghost** [comment]
Thank you!

**Pull request closed without merging**
