### PR TITLE
mark "type" parameter of "get watchlist" methods as optional

### PR DESCRIPTION
**Pull request by janpio**
You can also get a list of all watchlist items:
http://docs.trakt.apiary.io/#reference/sync/get-watchlist/get-watchlist http://docs.trakt.apiary.io/#reference/users/watchlist/get-watchlist

### CODE REVIEW

**Comment by vankasteelj** [comment]
is it optional though?

**Comment by janpio** [comment]
That's what it say when you hover over the "empty" dot next to the `type` explanation on the docs - and I can make requests with `/show`, `/season`, `/episode` and `/movie` - and without. (The usage of some optional parameters in paths is really confusing in the API...)

**Comment by vankasteelj** [comment]
Indeed! I never saw that little dot thingy. Well, I'll test to be sure, and then I'll have to check the entire methods just to be safe. Great catch

**Comment by vankasteelj** [comment]
see the dev branch ;)

**Comment by janpio** [comment]
Great.

(PRs better to the dev branch?)

**Comment by vankasteelj** [comment]
yes, so we don't screw up docs until release of an actual update, now that docs are in the repo itself

**Comment by vankasteelj** [comment]
possible issue with search/text : type is set as mandatory on the docs, not in the json

**Pull request closed without merging**
